version: '3.8'

services:
  iot-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iot-manager-app
    environment:
      - DISPLAY=:99
      - ELECTRON_DISABLE_SANDBOX=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    stdin_open: true
    tty: true
